export const DOM = {
	inputParameters: document.querySelectorAll(".input"),
	calcButton: document.querySelector("#calculate-btn"),
	amountInput: document.getElementById("input-amount-box"),
	termInput: document.getElementById("input-term"),
	rateInput: document.getElementById("input-rate"),
	repayType: document.querySelector("#repayment-btn"),
	interestType: document.querySelector("#interest-only-btn"),
	amountError: document.querySelector("#amount-err-msg"),
	termError: document.querySelector("#term-err-msg"),
	rateError: document.querySelector("#rate-err-msg"),
	typeError: document.querySelector("#type-err-msg"),
	resultDefault: document.querySelector(".results-default"),
	resultActive: document.querySelector(".results-active"),
	resultNum: document.querySelector(".result-num"),
	bigNum: document.querySelector(".big-num"),
	smallNumTitle: document.querySelector(".small-num-label"),
	smallNum: document.querySelector(".small-num"),
	termBox: document.querySelector(".term-box"),
	termDiv: document.querySelector("#input-term"),
	rateBox: document.querySelector(".rate-box"),
	rateDiv: document.querySelector("#input-rate"),
	clearButton: document.getElementById("clear-btn"),
};
